apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: demo-voting-app
spec:
  ports:
    - port: 5432 #service port
      targetPort: 5432 #container port
  selector:
    component: postgre
    app: demo-voting-app
