apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: demo-voting-app
spec:
  ports:
    - port: 6379 #service port
      targetPort: 6379 #container port
  selector:
    component: redis
    app: demo-voting-app
