apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 80 #service port
      targetPort: 80 #container port
      nodePort: 30005
  selector:
    component: result
    app: demo-voting-app
