apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 80 #service port
      targetPort: 80 #container port
      nodePort: 30004
  selector:
    component: voting
    app: demo-voting-app
