apiVersion: v1
kind: Pod
metadata:
  name: postgre-pod
  labels:
    component: postgre
    app: demo-voting-app #same since all pods are part of the same application
spec:
  containers:
    - name: postgre
      image: postgres:9.4
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_DB
          value: "voting"
