apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    component: redis
    app: demo-voting-app #same since all pods are part of the same application
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379
