apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    component: result
    app: demo-voting-app #same since all pods are part of the same application
spec:
  containers:
    - name: voting-app-result
      image: bibekk477/voting-app-result:v1
      ports:
        - containerPort: 80
