apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    component: voting
    app: demo-voting-app
spec:
  containers:
    - name: voting-app
      image: bibekk477/voting-app:v1
      ports:
        - containerPort: 80
